apiVersion: v2
name: screenplay
description: A Helm chart for deploying ScreenPlay 
version: 0.1.0
appVersion: 2.0.0
dependencies:
  - name: postgres
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
